volumes:
  postgr_data: {}
  pgadmin-data:

services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    env_file:
      - ./.env
    environment:
      DB_HOST: user3232@domainname.com
    ports:
      - "5432:5432"
    volumes:
      - postgr_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8882:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - pgadmin
